### ISSUE TITLE
Tener acceso de dev administrador para explorar wordpress

### ISSUE THREAD

**Issue by basicavisual** [ponentesincausa/datos1x1#13]
que @cintiadu facilite acceso de administrador para hacer la expedición de datos.

**Comment by juliogontor** [comment]
En esta parte sería la administración al wordpress backend y la parte de conexión a la BD

**Comment by basicavisual** [comment]
Resuelto. Por seguridad sólo los devs listados en el readme tienen acceso. Pedirlo si van a participar en este.
