### ISSUE TITLE
Definir como se descargan los formularios 

### ISSUE THREAD

**Issue by cintiadu** [ponentesincausa/datos1x1#5]

**Comment by DonPepperony** [comment]
Hola c: pues buscando encontré una posible solución, sin embargo estaría bien que @iorch lo checara mas a fondo y diga que tan viable o no es.

http://www.howtogeek.com/howto/44791/how-to-backup-your-web-based-email-account-using-thunderbird/

El primero es descargar los archivos a una base de datos local usando thunderbird. El problema es que los archivos que maneja son .msf, .eml, etc y son complicados de utilizar en sql o en una base de datos en si. Pero en otro link ponen que en DBMail (algo hecho para linux) se puede exportar o manejar los datos para una base de datos en SQL 

http://stackoverflow.com/questions/8981441/export-emails-from-thunderbird-to-sql-server

http://www.dbmail.org/

Algo así. Saludos!

**Comment by basicavisual** [comment]
Otra alternativa sería usar un google script que importe los correos a una spreadsheet, de ahí sería fácil pasarlos a una db.

https://developers.google.com/apps-script/reference/gmail/?csw=1

https://developers.google.com/apps-script/reference/gmail/gmail-app

https://developers.google.com/apps-script/guides/sheets

El script debe:
-  Abrir un google spreadsheet y nombrarlo
- Crear las columnas pertinentes*
- Accesar la cuenta de gmail
- Leer todos los threads
- Para cada correo, extraer cada dato
- Pasar todos los datos en una nueva fila a columnas definidas en el google sheet

---

El formulario se llena a través de wordpress, por lo que los campos y el formato son siempre los mismos. El único campo problemático es el de localidad, que el usuario escribe manualmente por lo que va a arrojar nombres de ciudades diferentes (e.g. Aguascalientes, ags, aguascalientes, etc.)

Muestra de formulario

Asunto: FOTO PARA 1X1

TÍTULO DE LA FOTO:
 Gotas

NOMBRE:
 Jane Doe

CORREO ELECTRÓNICO:
 janedoe@hotmail.com

SEXO:
Femenino

EDAD:
 15

WEBSITE:
 https://www.instagram.com/janedoe/

TU CIUDAD:
 Aguascalientes; Ags

Debes estar de acuerdo con nuestro Aviso de privacidad:
 Sí, estoy de acuerdo.

---

Una dificultad adicional es el attachment. El script podría guardar el attachment en un google drive e imprimir el link en una de las columnas.

**Comment by basicavisual** [comment]
Ok relacionado al issue #7 : La página está construida en wordpress y el workflow es que el usuario llena el formulario y un servicio de correo lo envía a una cuenta de gmail. Es altamente probable que wordpress esté guardando todos esos correos ya en una base de datos, por lo que no habría que extraer nada. Copio esto en el issue 7. No se pueden tomar acciones hasta confirmar esto.

**Comment by basicavisual** [comment]
no es necesario, ver el issue #2
