### ISSUE TITLE
Agregar README del proyecto

### ISSUE THREAD

**Issue by basicavisual** [ponentesincausa/datos1x1#6]
Agrega README del proyecto como especificado aquí:

Primera prioridad: https://github.com/CodeandoGuadalajara/empieza-aqui/blob/master/spec.md
Opcional: https://github.com/MrOutis/GitHub-Simple#desarrollo-guiado-por-readme

**Comment by ponentesincausa** [comment]
pensándolo bien, habrá que empezar con este documento: https://github.com/CodeandoGuadalajara/empieza-aqui/blob/master/spec.md
