### ISSUE TITLE
Accesar la base de datos

### ISSUE THREAD

**Issue by basicavisual** [ponentesincausa/datos1x1#8]
La base de datos fotográfica se encuentra en wordpress. Este issue es para rastrear la base de datos mediante la cual el administrador sube las entradas. Por el momento la única persona que tiene la clave es @cintiadu posteriormente se buscará constuir un api para no depender de esto.

**Comment by juliogontor** [comment]
Puede ser api, algún plugin o enseñar a usar alguna herramienta de consulta de datos.

**Comment by basicavisual** [comment]
Listo, sólo los integrantes que aparecen en el readme tienen acceso por seguridad. Consultar con ellos y posteriormente vamos a montar un entorno de test.
